# These are supported funding model platforms

github: sgloutnikov
patreon: neterraproxy
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=Y34UM4VDRY532&currency_code=USD&source=url
